'use client';

import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';

type Language = 'so' | 'en';

interface ShopLanguageContextType {
    lang: Language;
    toggle: () => void;
    t: (key: string) => string;
}

const ShopLanguageContext = createContext<ShopLanguageContextType | null>(null);

// ============================================================
// TURJUMAADKA - All Shop Translations (SO + EN)
// ============================================================
const translations: Record<Language, Record<string, string>> = {
    so: {
        // === HEADER ===
        search_placeholder: "Raadi alaab, rasiid, macaamiil...",
        shop_manager: "Maamulaha Dukaanku",
        admin: "Maamule",

        // === COMMON ACTIONS ===
        add_new: "Kudar Cusub",
        save: "Keydi",
        cancel: "Jooji",
        delete: "Tirtir",
        edit: "Wax ka beddel",
        view_all: "Dhamaan Arag",
        back: "Noqo",
        search: "Raadi",
        filter: "Shaandhee",
        export: "Soo Saarid",
        print: "Daabac",
        close: "Xidh",
        confirm: "Xaqiiji",
        loading: "Waa la rarayaa.",
        no_data: "Xog lama helin.",
        success: "Guul",
        error: "Khalad",
        submit: "Dir",
        clear: "Nadiifi",
        refresh: "Cusoobaysi",
        pay_now: "Hadda Bixi",
        pay: "Bixi",
        receive: "Qaado",
        status: "Xaalad",
        name: "Magac",
        phone: "Telefoon",
        email: "Imiil",
        address: "Cinwaan",
        notes: "Xusuus-qoryo",
        date: "Taariikhda",
        amount: "Lacagta",
        total: "Wadarta",
        balance: "Haraaga",
        type: "Nooca",
        category: "Qaybta",
        description: "Sharaxaad",
        quantity: "Tiro",
        price: "Qiimaha",
        unit: "Cutub",
        actions: "Ficilka",
        yes: "Haa",
        no: "Maya",
        active: "Shaqaynaya",
        inactive: "Joogsaday",
        paid: "La Bixiyay",
        unpaid: "Lama Bixin",
        partial: "Qaar",
        overdue: "Waqtigiisii dhaafay",

        // === DASHBOARD ===
        system_online: "Nidaamka Shaqaynaya",
        dashboard_title: "Murayada Ganacsiga",
        live_sync: "Cusboonaysiinta Tooska ah",
        start_new_sale: "Iib Cusub Bilow",
        total_revenue: "Dakhliga Guud",
        net_profit: "Faa'iidada Nadiifka",
        real_profit: "Faa'iido Dhabta",
        orders: "Dalabyo",
        total_sales: "Wadarta Iibka",
        products: "Alaabta",
        live_items: "Alaab Jira",
        low_stock: "Kayd Hooseeya",
        action_needed: "Tallaabo Qaado",
        stock_solid: "Kayd Fiican",
        vs_last_week: "usbuucii hore",
        sales_performance: "Guud-marka Iibka",
        week_trend: "Isbeddelka Usbuucii",
        momentum: "XOOGGA",
        receivables: "Lacagta La Qaadanayo",
        payables: "Lacagta La Bixinayo",
        no_debtors: "Deynle lama helin.",
        no_payables: "Lacag la bixin ma jirto.",
        profit_leaders: "Ugu Faa'iidada Badan",
        expense_mix: "Kharashka Kala Saaran",
        sold: "la iibbiyay",
        debt_aging: "Da'ada Daymaha (AR)",
        current_debt: "Hadda (0-7m)",
        late_debt: "Daahay (8-30m)",
        overdue_debt: "Waqti dhaafay (30m+)",
        live_activity: "Dhaqdhaqaaqyada Hadda",
        predictive_stockouts: "Alaab Dhammaan Doonta",
        inventory_optimized: "Kaydku Fiican yahay",
        refill_now: "Hadda Buuxi",
        days_left: "maalin baqan",

        // === AI SECTION ===
        ai_intelligence: "Xasaarada AI",
        ai_proactive_guard: "AI Ilaalin Toos ah",
        smart_insights: "Faahfaahin Caqli-gal",
        inventory_risk: "Khatar Kaydka",
        inventory_risk_msg: "alaab ayaa heer hooseeya. Degdeg soo iibso si aadan iib uga dhumiyoon.",
        cash_flow_alert: "Dignaanka Lacageed",
        cash_flow_msg: "waxay ku xidhan tahay lacagta la qaadanayo. La xiriir deynleyda.",
        sales_dip: "Hoos u dhac Iibka",
        sales_dip_msg: "Dakhligu hoos buu ugu dhacay usbuucii hore. Alaabta ugu badan arag.",
        system_optimized: "Nidaamku Waa Fiican: AI Waxuu Ilaalinayaa Faa'iidadaada",
        revlo_expert: "Khabiirka Revlo",
        talk_to_data: "La hadal xogtaada ganacsiga",
        ask_placeholder: "Su'aashaada halkan ku qor...",
        ask_anything: "Wax alla wax i weydii\nIibka, Kaydka ama Faa'iidada",

        // === INVENTORY ===
        inventory_title: "Kaydka Alaabta",
        inventory_desc: "Maamusha alaabta iyo kaydka",
        add_product: "Alaab Kudar",
        product_name: "Magaca Alaabta",
        buying_price: "Qiimaha Iibsashada",
        selling_price: "Qiimaha Iibka",
        in_stock: "Kaydka Jira",
        min_stock: "Ugu yaraan",
        sku: "Lambarka SKU",
        location: "Goobta",
        supplier: "Baayi'aha",
        all_categories: "Dhammaan Qaybaha",
        all_status: "Dhammaan Xaaladaha",
        stock_ok: "Kayd Fiican",
        low_stock_label: "Kayd Hooseeya",
        out_of_stock: "Alaab Ma Jirto",
        add_stock: "Kayd Kudar",
        adjust_stock: "Kayd Saxo",
        adjust: "Saxo",
        bulk_import: "Soo dejinta Isku-mar",
        products_found: "alaab la helay",
        items: "alaab",
        item: "alaab",

        // === POS ===
        pos_title: "Iibka Degdega",
        pos_desc: "Cashier-ka / Iibka Tooska",
        cart: "Gaari-Iibka",
        cart_empty: "Gaari-Iibku waa madhan yahay",
        add_to_cart: "Gaari-Iibka Kudar",
        remove: "Ka Saar",
        checkout: "Lacag Bixin",
        subtotal: "Wadarta Yar",
        tax: "Canshuurta",
        discount: "Dhimista",
        grand_total: "Wadarta Guud",
        payment_method: "Habka Lacag Bixinta",
        cash: "Lacag Gacanta",
        mobile: "Lacag Telefoonka",
        card: "Kaarka",
        receipt: "Rasiid",
        new_sale: "Iib Cusub",
        complete_sale: "Iibka Dhamays",
        customer_optional: "Macmiilka (ikhtiyaari)",
        search_products: "Raadi alaabta...",
        items_in_cart: "alaab gaari-iibka ku jira",

        // === SALES ===
        sales_title: "Taariikhda Iibka",
        sales_desc: "Dhammaan iibiyaasha iyo rasiidyada",
        invoice_number: "Lambarka Invoice-ka",
        customer: "Macmiilka",
        sale_date: "Taariikhda Iibka",
        items_sold: "Alaab la Iibbiyay",
        payment_status: "Xaaladda Lacagta",
        view_invoice: "Invoice Arag",
        all_time: "Weligeed",
        today: "Maanta",
        this_week: "Usbuuca",
        this_month: "Bishaan",
        no_sales: "Iib lama helin xilligaan.",

        // === PURCHASES ===
        purchases_title: "Iibsashada Alaabta",
        purchases_desc: "Alaabta dukaanka lagu soo iibsaday",
        purchase_order: "Dalabka Alaabta",
        vendor: "Baayi'aha",
        expected_date: "Taariikhda La Filayo",
        received: "La Helay",
        pending: "Sugaya",
        create_purchase: "Dalabka Cusub",
        add_purchase: "Iibsi Alaab",
        no_purchases: "Iibsi lama helin.",

        // === CUSTOMERS ===
        customers_title: "Macaamiisha",
        customers_desc: "Xogta dadka wax ka iibsada",
        add_customer: "Macmiil Kudar",
        customer_name: "Magaca Macmiilka",
        customer_type: "Nooca",
        individual: "Shaqsi",
        business: "Ganacsato",
        outstanding_balance: "Daynta Hadhay",
        no_balance: "Dayn ma laha",
        no_customers: "Macaamiil lama helin.",
        contact: "Xiriir",
        credit_limit: "Xaddiga Deynta",
        last_purchase: "Iibsashadii Ugu Dambeysay",

        // === VENDORS ===
        vendors_title: "Baayi'iinta",
        vendors_desc: "Kuwa aad alaabta ka iibsato",
        add_vendor: "Dukaan Kudar",
        vendor_name: "Magaca Baayi'aha",
        products_services: "Alaab/Adeegyo",
        contact_person: "Qofka La Xiriira",
        total_purchases: "Wadarta Iibsashada",
        no_vendors: "Dukaan lama helin.",

        // === EMPLOYEES ===
        employees_title: "Shaqaalaha",
        employees_desc: "Maaraynta shaqaalaha",
        add_employee: "Shaqaale Kudar",
        employee_name: "Magaca Shaqaalaha",
        role: "Shaqada",
        salary: "Mushaharka",
        start_date: "Taariikhda Bilowga",
        is_active: "Waa Firfircoon",
        no_employees: "Shaqaale lama helin.",

        // === ACCOUNTING ===
        accounting_title: "Xisaabaadka",
        accounting_desc: "Maaraynta lacagaha iyo xisaabaadka",
        accounts: "Xisaabaadka",
        transactions_title: "Dhaqdhaqaaqyada",
        journal_title: "Diiwaanka Xisaabaadka",
        ledger_title: "Warqadaha Xisaabaadka",
        payables_title: "Lacagta La Bixinayo",
        receivables_title: "Lacagta La Qaadanayo",
        reconciliation_title: "Lamaaneysiinta Bangiga",
        tax_title: "Canshuurta",
        till_title: "Kaashka Dukaanku",
        assets_title: "Hantida Joogtada",
        total_balance: "Haraaga Guud",
        deposit: "Geli",
        withdraw: "Saar",
        transfer: "Wareeji",
        account_name: "Magaca Xisaabta",
        account_type: "Nooca Xisaabta",
        opening_balance: "Haraagii Bilowga",
        add_account: "Xisaab Kudar",
        no_accounts: "Xisaab lama helin.",
        bank: "Bangiga",
        mobile_money: "Lacagta Talafonka",
        cash_account: "Lacag Gacanta",
        po_number: "PO Lambarka",
        due_date: "Waqtiga La Bixinayo",
        amount_due: "Lacagta La Bixinayo",
        no_payables_found: "Lacag la bixin ma jirto.",
        no_receivables: "Lacag la qaadan ma jirto.",

        // === REPORTS ===
        reports_title: "Warbixinada",
        reports_desc: "Xaaladda ganacsiyadaada",
        finance_report: "Warbixinta Maaliyadda",
        profit_loss: "Faa'iido iyo Khasaare",
        sales_report: "Warbixinta Iibka",
        inventory_report: "Warbixinta Kaydka",
        expense_report: "Warbixinta Kharashka",
        balance_sheet: "Miisaanka Maaliyadda",
        low_stock_report: "Warbixinta Kaydka Hooseeya",
        top_products_report: "Alaabta Ugu Badan Iibka",
        categories_report: "Warbixinta Qaybaha",
        aging_report: "Warbixinta Da'ada Daymaha",
        total_revenue_label: "Dakhliga Guud",
        total_expenses: "Kharashka Guud",
        cost_of_goods: "Qiimaha Alaabta",
        gross_profit: "faaiidada guud",
        net_cash_flow: "Lacagta Tooska",
        this_year: "Sanadkan",
        last_7_days: "7 Maalmood",
        expense_breakdown: "Kharashka Kala Saaran",
        purchase_payment: "Lacagta Iibsashada",
        total_in: "Waxaa Galay",
        total_out: "Waxaa Baxay",
        margin: "Reebka",
        sales_transactions: "Iibiyaasha",

        // === MANUAL ENTRY ===
        manual_entry_title: "Gelin Rasiidka Gacanta",
        manual_entry_desc: "Rasiidyada si degdeg ah u geli",
        receipt_number: "Lambarka Rasiidka",
        entry_date: "Taariikhda",
        add_item: "Shay Kudar",
        remove_item: "Shay Ka Saar",
        save_receipt: "Rasiidka Keydi",
        new_entry: "Gelin Cusub",

        // === SETTINGS ===
        settings_title: "Goobadka",
        settings_desc: "Habaynta nidaamka",
        company_info: "Xogta Shirkadda",
        company_name: "Magaca Shirkadda",
        tax_rate: "Heerka Canshuurta",
        currency: "Lacagta Nooca",
        receipt_header: "Madaxa Rasiidka",
        receipt_footer: "Hoosta Rasiidka",
        save_settings: "Goobadka Kaydi",
        logo: "Astaanta Shirkadda",
        upload_logo: "Astaanta Soo Geli",
        language: "Luuqadda",
        theme: "Muuqaalka",
        whatsapp: "WhatsApp",
        connect_whatsapp: "WhatsApp-ka Xir",
        disconnect: "Ka Xidh",

        // === PAYROLL ===
        payroll_title: "Mushaharka",
        payroll_desc: "Bixinta mushaharka shaqaalaha",
        total_payroll: "Mushaharka Guud",
        paid_this_month: "Bishaan La Bixiyay",
        remaining_salary: "Mushaharka Hadhay",
        fully_paid: "Si Buuxda La Bixiyay",
        pay_salary: "Mushaharka Bixi",
        pay_extra: "Dheeri Bixi",
        sal_balance: "Mushaharka Hadhay",
        last_payment: "Bixintii Ugu Dambeysay",
        never_paid: "Wali lama bixin",
        confirm_payment: "Bixinta Xaqiiji",
        history: "Taariikhda",
        optional: "Ikhtiyaari",
        "e.g_advance": "Tusaale: Saldhig, Advance...",

        // === RECONCILIATION ===
        reconciliation_desc: "Lamaaneysi xisaabaadka nidaamka iyo bangiga",
        upload_statement: "Xaaladda Bangiga Soo Geli",
        upload_statement_desc: "CSV ama PDF-ka xaaladda bangiga soo geli si toos ah loo lamaaneeyo.",
        upload_bank_statement: "Xaaladda Bankiga Soo Geli",
        matched: "La Lamaaneeye",
        unmatched: "Lama Lamaaneeyn",
        pending_review: "Sugaya Dib-u-eegis",

        // === TILL ===
        till_desc: "Maaraynta kaashka dukaanku",
        open_till: "Kaadhiga Fur",
        close_till: "Kaadhiga Xidh",
        opening_cash: "Lacagta Bilowga",
        closing_cash: "Lacagta Xidhitaanka",
        cash_sales: "Iibka Lacagta",
        till_difference: "Kala Duwanaanta",

        // === ASSETS ===
        assets_desc: "Hantida joogtada ee dukaanka",
        add_asset: "Hanti Kudar",
        asset_name: "Magaca Hantida",
        asset_type: "Nooca Hantida",
        purchase_date: "Taariikhda Iibsashada",
        current_value: "Qiimaha Hadda",
        depreciation: "Hoos u dhaca Qiimaha",
        depreciate: "Qiime Hoos u dhac",
        no_assets: "Hanti lama helin.",

        // === TAX ===
        tax_desc: "Xisaabinta canshuurta",
        tax_period: "Xilliga Canshuurta",
        taxable_sales: "Iibka La Cashuuray",
        tax_collected: "Canshuurta La Ururiyay",
        tax_paid: "Canshuurta La Bixiyay",
        net_tax: "Canshuurta Nadiifka",

        // === JOURNAL ===
        journal_desc: "Diiwaanka dhaqdhaqaaqyada xisaabaadka",
        debit: "Debit",
        credit: "Credit",
        entry_number: "Lambarka Galintu",
        no_journal_entries: "Diiwaano lama helin.",

        // === LEDGER REPORT ===
        ledger_desc: "Diiwaanka xisaabaadka kasta",
        select_account: "Xisaab Dooro",
        opening_balance_label: "Haraagii Bilowga",
        closing_balance: "Haraagii Xidhitaanka",
        no_ledger: "Xog lama helin xisaabtaan.",

        // === AGING REPORTS ===
        customer_aging: "Da'ada Daymaha Macaamiisha",
        customer_aging_desc: "Lacagta ay macaamiisha ku leeyihiin wakhtiga",
        vendor_aging: "Da'ada Daymaha Dukaamada",
        vendor_aging_desc: "Lacagta aad dukaamada u leedahay wakhtiga",
        age_0_30: "0 - 30 Maalin",
        age_31_60: "31 - 60 Maalin",
        age_61_90: "61 - 90 Maalin",
        age_90_plus: "90+ Maalin",
        no_aging_data: "Dayn lama helin.",

        // === BALANCE SHEET ===
        balance_sheet_desc: "Hantida, Daymaha, iyo Maalka",
        assets_section: "Hantida",
        liabilities: "Daymaha",
        equity: "Maalka",
        current_assets: "Hantida Hadda",
        fixed_assets_label: "Hantida Joogtada",
        total_assets: "Wadarta Hantida",
        total_liabilities: "Wadarta Daymaha",
        total_equity: "Wadarta Maalka",
        cash_and_bank: "Lacagta & Bangiga",
        inventory_value: "Qiimaha Kaydka",
        accounts_receivable: "Lacagta La Qaadanayo",
        accounts_payable: "Lacagta La Bixinayo",

        // === CATEGORIES REPORT ===
        categories_desc: "Iibka iyo faa'iidada qaybta kasta",
        category_name: "Magaca Qaybta",
        total_sold: "Wadarta la Iibbiyay",
        total_profit: "Faa'iidada Guud",
        profit_margin: "Boqolleyda Faa'iidada",
        no_categories: "Qaybas lama helin.",

        // === TOP PRODUCTS REPORT ===
        top_products_desc: "Alaabta ugu badan iibka iyo faa'iidada",
        rank: "Goobta",
        revenue: "Dakhliga",
        profit: "Faa'iidada",
        units_sold: "Cutub la Iibbiyay",
        no_top_products: "Alaab lama helin.",

        // === LOW STOCK REPORT ===
        low_stock_desc: "Alaabta u baahan dib u buuxinta",
        current_stock: "Kaydka Jira",
        minimum_stock: "Kaydka ugu Yar",
        shortage: "Yaraan",
        reorder: "Dib u Dalabo",
        no_low_stock: "Dhammaan alaabtu kaydka waa fiican tahay.",

        // === PURCHASES extra (new keys only) ===
        payment_recorded: "Lacag La Diiwangeliyay",
        settlement_for: "Lacag-bixin waxay u tahay",

        // === INVENTORY DETAILS & EDIT ===
        product_not_found: "Alaab lama helin",
        back_to_inventory: "Ku noqo Kaydka",
        print_label: "Daabac Lebelka",
        product_overview: "Guudmarka Alaabta",
        no_description: "Ma jirto faah-faahin alaabtan lagu daray.",
        catalog_category: "Qaybta Alaabta",
        primary_supplier: "Baayi'aha Koowaad",
        direct_import: "Soo Dejin Toos ah",
        barcode_label_assets: "Lebelka Barcode & Xogta",
        print_label_template: "Daabac Tusaalaha Lebelka",
        barcode_usage_msg: "U isticmaal barcode-kan iibinta tooska ah iyo la socoshada kaydka.",
        unique_sku_required: "SKU Gaar ah ayaa Loo Baahan yahay",
        operational_history: "Taariikhda Dhaqdhaqaaqa",
        no_history_recorded: "Taariikh hore lama diiwaangelin",
        market_valuation: "Qiimaha Suuqa",
        stock_value: "Qiimaha Kaydka",
        est_profit: "Qiyaasta Faa'iidada",
        financial_performance: "Xaaladda Maaliyadeed",
        unit_profit: "Faa'iidada Halkii Xabo",
        roi_efficiency: "Hufnaanta Faa'iidada (ROI)",
        calc_based_msg: "Waxaa lagu xisaabiyay qiimaha iibsiga iyo qiimaha iibka ee hadda.",
        stock_intelligence: "Xogta Kaydka Alaabta",
        current_count: "Tirada Hadda",
        system_reports_units: "Nidaamku wuxuu muujinayaa kaydka jira",
        reorder_point: "Barta Dib-u-dalbashada",

        // === INVENTORY ADD / EDIT ===
        edit_product: "Wax Ka Bedel Alaabta",
        update_product_info: "Cusboonaysii macluumaadka alaabta iyo qiimaha.",
        basic_information: "Macluumaadka Asaasiga ah",
        pricing_and_stock: "Qiimaha & Kaydka",
        profit_margin_label: "Faa'iidada Reebka",
        profit_per_unit: "Faa'iido halkii xabo:",
        min_stock_alert: "Baqdinta Kaydka Hoose",
        update_product: "Cusboonaysii Alaabta",
        add_new_category: "Kudar Qayb Cusub",
        add_category: "Kudar Qaybta",
        add_new_supplier: "Kudar Baayi'e Cusub",
        supplier_name: "Magaca Baayi'aha",
        contact_info_optional: "Xogta Xiriirka (Ikhtiyaari)",
        add_new_product: "Kudar Alaab Cusub",
        create_new_item_msg: "Ku samee shay cusub diiwaankaaga kaydka.",
        sku_label: "SKU (Lambarka Aqoonsiga Kaydka)",
        initial_stock: "Tirada Kaydka Bilowga",
        low_stock_alert_level: "Heerka Baqdinta Kaydka Hoose",
        notify_stock_falls: "Waan ku soo ogeysiin doonnaa marka kaydku ka hooseeyo tiradan.",
        saving: "Waa la kaydinayaa...",
        save_product: "Kaydi Alaabta",

        // === STOCK ADJUSTMENT ===
        stock_adjustment: "Hagaajinta Kaydka",
        correct_inventory_msg: "Sax tirada kaydka wixii xumaaday, lumay, ama is-waafajin.",
        select_product: "Dooro Alaabta",
        search_name_sku: "Raadi magac ama SKU...",
        current_stock_label: "Kaydka Hadda:",
        change_label: "Beddel",
        adjustment_details: "Faahfaahinta Hagaajinta",
        remove_stock: "Ka Saar Kaydka",
        reason: "Sababta",
        reason_damage: "Burbur / Xumaaday",
        reason_loss: "Lumis / Xatooyo",
        reason_expired: "Waqtigeedu Dhacay",
        reason_correction: "Sakhitaan Kaydka",
        reason_found: "Shay La Helay",
        reason_return: "Macmiil Soo Celiyay",
        confirm_removal: "Xaqiiji Ka-saarista",
        confirm_addition: "Xaqiiji Ku-darista",

        // === BULK IMPORT ===
        cancel_import: "Jooji Soo-dejinta",
        bulk_import_inventory: "Soo-dejinta Tiro-badan",
        drag_drop_file: "Halkan ku soo rido ama jiido feylkaaga",
        supports_files: "Waxay taageertaa CSV, XLSX, XLS. Ugu badnaan 5MB.",
        browse_files: "Dooro Faylasha",
        need_template: "Ma u baahan tahay tusaale fayl (Template)?",
        download_template_msg: "Soo dejiso tusaale Excel-kayaga si aad si habsami leh ugu soo geliso xogta.",
        download: "Soo dejiso",
        preview_data: "Horudhaca Xogta",
        review_data_msg: "Eeg xogtaada intaanad soo gelinin.",
        valid: "Sax",
        invalid: "Khaldan",
        import_items: "Soo Daji",
        issues: "Dhibaatooyin",
        importing_products: "Waa la soo dejinayaa...",
        please_wait_process: "Fadlan sug inta aanu socodsiinayno kaydkaaga.",
        import_completed_errors: "Soo dejinta waa dhammaatay iyadoo leh khaladaad",
        review_issues_msg: "Alaabooyinka qaar lama soo dejin karo. Eeg khaladaadka hoose si aad u saxdo feylkaaga Excel.",
        successful: "Guulaystay",
        failed: "Fashilmay",
        failure_details: "Faahfaahinta Fashilka iyo Talooyinka",
        how_to_fix: "Sida Loo Saxo",
        proceed_to_inventory: "Ku soco Kaydka Alaabta",
        re_upload_file: "Markale Soo Geli Faylka La Saxay",
        import_successful: "Soo dejintu Waa Guul!",
        view_inventory: "Arag Kaydka",
        import_more: "Soo Geli Kuwo Kale",

        // === INVENTORY LIST PAGE ===
        inventory_hub: "Kaydka",
        inventory_hub_highlight: "Alaabta",
        total_sku_label: "Wadarta SKU",
        stock_value_label: "Qiimaha Kaydka",
        low_stock_stat: "Kayd Hooseeya",
        out_of_stock_stat: "Wax Ma Harin",
        etb_view: "ETB",
        usd_view: "USD",
        view_details: "Faahfaahin Arag",
        edit_product_action: "Wax Ka Bedel",
        delete_product_action: "Tirtir Alaabta",
        in_stock_status: "Kaydka Ku Jira",
        low_stock_status: "Kayd Hooseeya",
        out_of_stock_status: "Wax Ma Harin",
    },

    en: {
        // === HEADER ===
        search_placeholder: "Search products, invoices, customers...",
        shop_manager: "Shop Manager",
        admin: "Admin",

        // === COMMON ACTIONS ===
        add_new: "Add New",
        save: "Save",
        cancel: "Cancel",
        delete: "Delete",
        edit: "Edit",
        view_all: "View All",
        back: "Back",
        search: "Search",
        filter: "Filter",
        export: "Export",
        print: "Print",
        close: "Close",
        confirm: "Confirm",
        loading: "Loading...",
        no_data: "No data found.",
        success: "Success",
        error: "Error",
        submit: "Submit",
        clear: "Clear",
        refresh: "Refresh",
        pay_now: "Pay Now",
        pay: "Pay",
        receive: "Receive",
        status: "Status",
        name: "Name",
        phone: "Phone",
        email: "Email",
        address: "Address",
        notes: "Notes",
        date: "Date",
        amount: "Amount",
        total: "Total",
        balance: "Balance",
        type: "Type",
        category: "Category",
        description: "Description",
        quantity: "Quantity",
        price: "Price",
        unit: "Unit",
        actions: "Actions",
        yes: "Yes",
        no: "No",
        active: "Active",
        inactive: "Inactive",
        paid: "Paid",
        unpaid: "Unpaid",
        partial: "Partial",
        overdue: "Overdue",

        // === DASHBOARD ===
        system_online: "System Online",
        dashboard_title: "Dashboard",
        live_sync: "Live Sync",
        start_new_sale: "Start New Sale",
        total_revenue: "Total Revenue",
        net_profit: "Net Profit",
        real_profit: "Real Profit",
        orders: "Orders",
        total_sales: "Total Sales",
        products: "Products",
        live_items: "Live items",
        low_stock: "Low Stock",
        action_needed: "Action needed",
        stock_solid: "Solid",
        vs_last_week: "vs last week",
        sales_performance: "Sales Performance",
        week_trend: "Week-over-Week Trend Analysis",
        momentum: "MOMENTUM",
        receivables: "Receivables",
        payables: "Payables",
        no_debtors: "No debtors found.",
        no_payables: "No payables found.",
        profit_leaders: "Profit Leaders",
        expense_mix: "Expense Mix",
        sold: "sold",
        debt_aging: "Debt Aging (AR)",
        current_debt: "Current (0-7d)",
        late_debt: "Late (8-30d)",
        overdue_debt: "Overdue (30d+)",
        live_activity: "Live Activity Audit",
        predictive_stockouts: "Predictive Stockouts",
        inventory_optimized: "Inventory Optimized",
        refill_now: "Refill Now",
        days_left: "d left",

        // === AI SECTION ===
        ai_intelligence: "AI Business Intelligence",
        ai_proactive_guard: "AI Proactive Guard",
        smart_insights: "Smart Insights",
        inventory_risk: "Inventory Risk",
        inventory_risk_msg: "items are critically low. Replenish soon to avoid lost sales.",
        cash_flow_alert: "Cash Flow Alert",
        cash_flow_msg: "is tied up in receivables. Follow up with debtors.",
        sales_dip: "Sales Dip Detected",
        sales_dip_msg: "Revenue dropped vs last week. Analyze top products.",
        system_optimized: "System Optimized: Gemini Guarding Your Profit",
        revlo_expert: "Revlo Expert",
        talk_to_data: "Talk to your business data",
        ask_placeholder: "Type your question...",
        ask_anything: "Ask me anything about\nSales, Inventory or Profit",

        // === INVENTORY ===
        inventory_title: "Inventory",
        inventory_desc: "Manage your products and stock",
        add_product: "Add Product",
        product_name: "Product Name",
        buying_price: "Buying Price",
        selling_price: "Selling Price",
        in_stock: "In Stock",
        min_stock: "Min Stock",
        sku: "SKU",
        location: "Location",
        supplier: "Supplier",
        all_categories: "All Categories",
        all_status: "All Status",
        stock_ok: "In Stock",
        low_stock_label: "Low Stock",
        out_of_stock: "Out of Stock",
        add_stock: "Add Stock",
        adjust_stock: "Adjust Stock",
        adjust: "Adjust",
        bulk_import: "Bulk Import",
        products_found: "products found",
        items: "items",
        item: "item",

        // === POS ===
        pos_title: "Point of Sale",
        pos_desc: "Cashier / Retail Mode",
        cart: "Cart",
        cart_empty: "Cart is empty",
        add_to_cart: "Add to Cart",
        remove: "Remove",
        checkout: "Checkout",
        subtotal: "Subtotal",
        tax: "Tax",
        discount: "Discount",
        grand_total: "Grand Total",
        payment_method: "Payment Method",
        cash: "Cash",
        mobile: "Mobile Money",
        card: "Card",
        receipt: "Receipt",
        new_sale: "New Sale",
        complete_sale: "Complete Sale",
        customer_optional: "Customer (optional)",
        search_products: "Search products...",
        items_in_cart: "items in cart",

        // === SALES ===
        sales_title: "Sales History",
        sales_desc: "All sales transactions and invoices",
        invoice_number: "Invoice #",
        customer: "Customer",
        sale_date: "Sale Date",
        items_sold: "Items Sold",
        payment_status: "Payment",
        view_invoice: "View Invoice",
        all_time: "All Time",
        today: "Today",
        this_week: "This Week",
        this_month: "This Month",
        no_sales: "No sales found for this period.",

        // === PURCHASES ===
        purchases_title: "Purchases",
        purchases_desc: "Stock purchases from vendors",
        purchase_order: "Purchase Order",
        vendor: "Vendor",
        expected_date: "Expected Date",
        received: "Received",
        pending: "Pending",
        create_purchase: "New Purchase Order",
        add_purchase: "Add Purchase",
        no_purchases: "No purchases found.",

        // === CUSTOMERS ===
        customers_title: "Customers",
        customers_desc: "Manage your customer accounts",
        add_customer: "Add Customer",
        customer_name: "Customer Name",
        customer_type: "Type",
        individual: "Individual",
        business: "Business",
        outstanding_balance: "Outstanding Balance",
        no_balance: "No balance",
        no_customers: "No customers found.",
        contact: "Contact",
        credit_limit: "Credit Limit",
        last_purchase: "Last Purchase",

        // === VENDORS ===
        vendors_title: "Vendors",
        vendors_desc: "Manage your suppliers",
        add_vendor: "Add Vendor",
        vendor_name: "Vendor Name",
        products_services: "Products/Services",
        contact_person: "Contact Person",
        total_purchases: "Total Purchases",
        no_vendors: "No vendors found.",

        // === EMPLOYEES ===
        employees_title: "Employees",
        employees_desc: "Manage your staff",
        add_employee: "Add Employee",
        employee_name: "Employee Name",
        role: "Role",
        salary: "Salary",
        start_date: "Start Date",
        is_active: "Active",
        no_employees: "No employees found.",

        // === ACCOUNTING ===
        accounting_title: "Accounting",
        accounting_desc: "Manage accounts and finances",
        accounts: "Accounts",
        transactions_title: "Transactions",
        journal_title: "Journal Entries",
        ledger_title: "General Ledger",
        payables_title: "Accounts Payable",
        receivables_title: "Accounts Receivable",
        reconciliation_title: "Bank Reconciliation",
        tax_title: "Tax Management",
        till_title: "Till Management",
        assets_title: "Fixed Assets",
        total_balance: "Total Balance",
        deposit: "Deposit",
        withdraw: "Withdraw",
        transfer: "Transfer",
        account_name: "Account Name",
        account_type: "Account Type",
        opening_balance: "Opening Balance",
        add_account: "Add Account",
        no_accounts: "No accounts found.",
        bank: "Bank",
        mobile_money: "Mobile Money",
        cash_account: "Cash",
        po_number: "PO #",
        due_date: "Due Date",
        amount_due: "Amount Due",
        no_payables_found: "No pending bills found.",
        no_receivables: "No receivables found.",

        // === REPORTS ===
        reports_title: "Reports",
        reports_desc: "Business intelligence & analytics",
        finance_report: "Financial Overview",
        profit_loss: "Profit & Loss",
        sales_report: "Sales Report",
        inventory_report: "Inventory Report",
        expense_report: "Expense Report",
        balance_sheet: "Balance Sheet",
        low_stock_report: "Low Stock Report",
        top_products_report: "Top Products",
        categories_report: "Categories Report",
        aging_report: "Aging Report",
        total_revenue_label: "Total Revenue",
        total_expenses: "Total Expenses",
        cost_of_goods: "Cost of Goods",
        gross_profit: "Gross Profit",
        net_cash_flow: "Net Cash Flow",
        this_year: "This Year",
        last_7_days: "Last 7 Days",
        expense_breakdown: "Expense Breakdown",
        purchase_payment: "Purchase Payment",
        total_in: "Total In",
        total_out: "Total Out",
        margin: "Margin",
        sales_transactions: "Sales Transactions",

        // === MANUAL ENTRY ===
        manual_entry_title: "Manual Receipt Entry",
        manual_entry_desc: "Quickly record receipts",
        receipt_number: "Receipt Number",
        entry_date: "Date",
        add_item: "Add Item",
        remove_item: "Remove Item",
        save_receipt: "Save Receipt",
        new_entry: "New Entry",

        // === SETTINGS ===
        settings_title: "Settings",
        settings_desc: "System configuration",
        company_info: "Company Information",
        company_name: "Company Name",
        tax_rate: "Tax Rate",
        currency: "Currency",
        receipt_header: "Receipt Header",
        receipt_footer: "Receipt Footer",
        save_settings: "Save Settings",
        logo: "Logo",
        upload_logo: "Upload Logo",
        language: "Language",
        theme: "Theme",
        whatsapp: "WhatsApp",
        connect_whatsapp: "Connect WhatsApp",
        disconnect: "Disconnect",

        // === PAYROLL ===
        payroll_title: "Payroll",
        payroll_desc: "Manage employee salary payments",
        total_payroll: "Total Payroll",
        paid_this_month: "Paid This Month",
        remaining_salary: "Remaining Salary",
        fully_paid: "Fully Paid",
        pay_salary: "Pay Salary",
        pay_extra: "Pay Extra",
        sal_balance: "Salary Balance",
        last_payment: "Last Payment",
        never_paid: "Never paid",
        confirm_payment: "Confirm Payment",
        history: "History",
        optional: "Optional",
        "e.g_advance": "e.g. Advance, Bonus...",

        // === RECONCILIATION ===
        reconciliation_desc: "Match system records with bank statements.",
        upload_statement: "Upload Statement",
        upload_statement_desc: "Import your CSV or PDF bank statement to start reconciling your accounts automatically.",
        upload_bank_statement: "Upload Bank Statement",
        matched: "Matched",
        unmatched: "Unmatched",
        pending_review: "Pending Review",

        // === TILL ===
        till_desc: "Manage your cash register",
        open_till: "Open Till",
        close_till: "Close Till",
        opening_cash: "Opening Cash",
        closing_cash: "Closing Cash",
        cash_sales: "Cash Sales",
        till_difference: "Difference",

        // === ASSETS ===
        assets_desc: "Manage your fixed assets",
        add_asset: "Add Asset",
        asset_name: "Asset Name",
        asset_type: "Asset Type",
        purchase_date: "Purchase Date",
        current_value: "Current Value",
        depreciation: "Depreciation",
        depreciate: "Depreciate",
        no_assets: "No assets found.",

        // === TAX ===
        tax_desc: "Tax calculation and reporting",
        tax_period: "Tax Period",
        taxable_sales: "Taxable Sales",
        tax_collected: "Tax Collected",
        tax_paid: "Tax Paid",
        net_tax: "Net Tax",

        // === JOURNAL ===
        journal_desc: "Record of all accounting entries",
        debit: "Debit",
        credit: "Credit",
        entry_number: "Entry #",
        no_journal_entries: "No journal entries found.",

        // === LEDGER REPORT ===
        ledger_desc: "Balance per account",
        select_account: "Select Account",
        opening_balance_label: "Opening Balance",
        closing_balance: "Closing Balance",
        no_ledger: "No transactions found for this account.",

        // === AGING REPORTS ===
        customer_aging: "Customer Aging Report",
        customer_aging_desc: "Outstanding balances by age",
        vendor_aging: "Vendor Aging Report",
        vendor_aging_desc: "Amounts owed to vendors by age",
        age_0_30: "0 - 30 Days",
        age_31_60: "31 - 60 Days",
        age_61_90: "61 - 90 Days",
        age_90_plus: "90+ Days",
        no_aging_data: "No outstanding balances found.",

        // === BALANCE SHEET ===
        balance_sheet_desc: "Assets, Liabilities & Equity",
        assets_section: "Assets",
        liabilities: "Liabilities",
        equity: "Equity",
        current_assets: "Current Assets",
        fixed_assets_label: "Fixed Assets",
        total_assets: "Total Assets",
        total_liabilities: "Total Liabilities",
        total_equity: "Total Equity",
        cash_and_bank: "Cash & Bank",
        inventory_value: "Inventory Value",
        accounts_receivable: "Accounts Receivable",
        accounts_payable: "Accounts Payable",

        // === CATEGORIES REPORT ===
        categories_desc: "Sales and profit by category",
        category_name: "Category",
        total_sold: "Total Sold",
        total_profit: "Total Profit",
        profit_margin: "Profit Margin",
        no_categories: "No categories found.",

        // === TOP PRODUCTS REPORT ===
        top_products_desc: "Best performing products by revenue",
        rank: "Rank",
        revenue: "Revenue",
        profit: "Profit",
        units_sold: "Units Sold",
        no_top_products: "No products found.",

        // === LOW STOCK REPORT ===
        low_stock_desc: "Products that need restocking",
        current_stock: "Current Stock",
        minimum_stock: "Min Stock",
        shortage: "Shortage",
        reorder: "Reorder",
        no_low_stock: "All products are well stocked.",

        // === PURCHASES extra (new keys only) ===
        payment_recorded: "Payment Recorded",
        settlement_for: "Settlement for",

        // === INVENTORY DETAILS & EDIT ===
        product_not_found: "Product not found",
        back_to_inventory: "Back to Inventory",
        print_label: "Print Label",
        product_overview: "Product Overview",
        no_description: "No detailed description provided for this catalog item.",
        catalog_category: "Catalog Category",
        primary_supplier: "Primary Supplier",
        direct_import: "Direct Import",
        barcode_label_assets: "Barcode Label & Assets",
        print_label_template: "Print Label Template",
        barcode_usage_msg: "Use this barcode for POS scanning and inventory tracking.",
        unique_sku_required: "Unique SKU Required",
        operational_history: "Operational History",
        no_history_recorded: "No historical data recorded",
        market_valuation: "Market Valuation",
        stock_value: "Stock Value",
        est_profit: "Est. Profit",
        financial_performance: "Financial Performance",
        unit_profit: "Unit Profit",
        roi_efficiency: "ROI Efficiency",
        calc_based_msg: "Calculated based on unit acquisition cost vs current listing price.",
        stock_intelligence: "Stock Intelligence",
        current_count: "Current Count",
        system_reports_units: "System reports active units",
        reorder_point: "Reorder Point",

        // === INVENTORY ADD / EDIT ===
        edit_product: "Edit Product",
        update_product_info: "Update product information and pricing.",
        basic_information: "Basic Information",
        pricing_and_stock: "Pricing & Stock",
        profit_margin_label: "Profit Margin",
        profit_per_unit: "Profit per unit:",
        min_stock_alert: "Min. Stock Alert",
        update_product: "Update Product",
        add_new_category: "Add New Category",
        add_category: "Add Category",
        add_new_supplier: "Add New Supplier",
        supplier_name: "Supplier Name",
        contact_info_optional: "Contact Info (Optional)",
        add_new_product: "Add New Product",
        create_new_item_msg: "Create a new item in your inventory catalog.",
        sku_label: "SKU (Stock Keeping Unit)",
        initial_stock: "Initial Stock Quantity",
        low_stock_alert_level: "Low Stock Alert Level",
        notify_stock_falls: "We'll notify you when stock falls below this number.",
        saving: "Saving...",
        save_product: "Save Product",

        // === STOCK ADJUSTMENT ===
        stock_adjustment: "Stock Adjustment",
        correct_inventory_msg: "Correct inventory levels for damages, loss, or differences.",
        select_product: "Select Product",
        search_name_sku: "Search by name or SKU...",
        current_stock_label: "Current Stock:",
        change_label: "Change",
        adjustment_details: "Adjustment Details",
        remove_stock: "Remove Stock",
        reason: "Reason",
        reason_damage: "Damage",
        reason_loss: "Loss / Theft",
        reason_expired: "Expired",
        reason_correction: "Inventory Correction",
        reason_found: "Found Item",
        reason_return: "Customer Return",
        confirm_removal: "Confirm Removal",
        confirm_addition: "Confirm Addition",

        // === BULK IMPORT ===
        cancel_import: "Cancel Import",
        bulk_import_inventory: "Bulk Import Inventory",
        drag_drop_file: "Drag & Drop your file here",
        supports_files: "Supports CSV, XLSX, XLS. Max 5MB.",
        browse_files: "Browse Files",
        need_template: "Need a template?",
        download_template_msg: "Download our pre-formatted Excel template to ensure smooth import.",
        download: "Download",
        preview_data: "Preview Data",
        review_data_msg: "Review your data before importing.",
        valid: "Valid",
        invalid: "Invalid",
        import_items: "Import Items",
        issues: "Issues",
        importing_products: "Importing Products...",
        please_wait_process: "Please wait while we process your inventory.",
        import_completed_errors: "Import Completed with Errors",
        review_issues_msg: "Some products couldn't be imported. Review the issues below to fix your Excel file.",
        successful: "Successful",
        failed: "Failed",
        failure_details: "Failure Details & Recommendations",
        how_to_fix: "How to Fix",
        proceed_to_inventory: "Proceed to Inventory",
        re_upload_file: "Re-upload Fixed File",
        import_successful: "Import Successful!",
        view_inventory: "View Inventory",
        import_more: "Import More",

        // === INVENTORY LIST PAGE ===
        inventory_hub: "Inventory",
        inventory_hub_highlight: "Hub",
        total_sku_label: "Total SKU",
        stock_value_label: "Stock Value",
        low_stock_stat: "Low Stock",
        out_of_stock_stat: "Out of Stock",
        etb_view: "ETB View",
        usd_view: "USD View",
        view_details: "View Details",
        edit_product_action: "Edit Product",
        delete_product_action: "Delete Product",
        in_stock_status: "In Stock",
        low_stock_status: "Low Stock",
        out_of_stock_status: "Out of Stock",
    }
};

// ============================================================
// PROVIDER
// ============================================================
export function ShopLanguageProvider({ children }: { children: React.ReactNode }) {
    const [lang, setLang] = useState<Language>('so');

    useEffect(() => {
        const saved = localStorage.getItem('shop-lang') as Language;
        if (saved === 'so' || saved === 'en') setLang(saved);
    }, []);

    const toggle = useCallback(() => {
        setLang(prev => {
            const next = prev === 'so' ? 'en' : 'so';
            localStorage.setItem('shop-lang', next);
            return next;
        });
    }, []);

    const t = useCallback((key: string): string => {
        return translations[lang][key] ?? translations['en'][key] ?? key;
    }, [lang]);

    return (
        <ShopLanguageContext.Provider value={{ lang, toggle, t }}>
            {children}
        </ShopLanguageContext.Provider>
    );
}

// ============================================================
// HOOK
// ============================================================
export function useShopLang() {
    const ctx = useContext(ShopLanguageContext);
    if (!ctx) throw new Error('useShopLang must be used inside ShopLanguageProvider');
    return ctx;
}
